/* eslint-disable @next/next/no-css-tags */
import { getAllFonts } from "@/lib/fonts";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "fonts.lonelil.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {getAllFonts().map((font, i) => {
          return (
            <link key={i} rel="stylesheet" href={`/fonts/${font}/use.css`} />
          );
        })}
      </head>
      <body className={"dark min-h-screen antialiased"}>{children}</body>
    </html>
  );
}
