name: Deploy to cdn.lonelil.com

on:
  push:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: "cdn"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: sylwit/install-b2-cli-action@v1.0.0
        env: 
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
      
      - name: Deploy
        run: b2 sync --delete --replaceNewer ./fonts b2://lonelilcdn/fonts/
